name: build
on: workflow_dispatch
jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Generate projects
        working-directory: src
        shell: cmd
        run: createallprojects.bat
      - name: Build
        working-directory: src
        shell: cmd
        run: msbuild everything.sln /p:Configuration=Release /m
      - name: List output
        if: always()
        shell: cmd
        run: dir /s /b game\*.dll
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: w_hl2-dlls
          path: game/mod_hl2/**/*.dll
          if-no-files-found: warn
